export const data = [
  {
    id: 1,
    category: 'Chair',
    featured: true,
    latest: false,
    title: 'Armchair with Head Rester',
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2018/01/armchair.jpg',
    price: 62,
  }, {
    id: 2,
    category: 'Sofa',
    featured: true,
    latest: false,
    title: 'Beige Living Room Sofa',
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2018/01/sofa.jpg',
    oldPrice: 659,
    price: 599,
  }, {
    id: 3,
    category: 'Table',
    featured: true,
    latest: false,
    title: 'Classic Wooden Table',
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2018/01/table.jpg',
    oldPrice: 90,
    price: 85,
  }, {
    id: 4,
    category: 'Table',
    featured: true,
    latest: false,
    title: 'Computer Table with Office Chair',
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2017/12/office-table.jpg',
    price: 775,
  }, {
    id: 5,
    category: 'Table',
    featured: false,
    latest: false,
    title: 'Corner Study Table with Chair',
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2018/01/desk-table.jpg',
    price: 459,
  }, {
    id: 6,
    category: 'Table',
    featured: false,
    latest: false,
    title: 'Desktop Table with Drawers',
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2018/01/study-table.jpg',
    oldPrice: 565,
    price: 529,
  }, {
    id: 7,
    category: 'Table',
    featured: false,
    latest: false,
    title: 'Dinning Table for Two',
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2018/01/dining-table.jpg',
    oldPrice: 422,
    price: 360,
  }, {
    id: 8,
    category: 'Sofa',
    title: 'Fancy Chairs',
    featured: false,
    latest: false,
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2018/01/fancy-chairs.jpg',
    price: 380,
  }, {
    id: 9,
    category: 'Chair',
    title: 'Fancy Single Chair',
    featured: false,
    latest: true,
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2017/11/chair.jpg',
    price: 199,
  }, {
    id: 10,
    category: 'Sofa',
    featured: false,
    latest: true,
    title: 'Modern White Round Sofa',
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2018/01/round-sofa.jpg',
    price: 599,
  }, {
    id: 11,
    category: 'Chair',
    featured: false,
    latest: true,
    title: 'Orange Recliner with Leg Rest',
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2018/01/pic53-free-img.jpg',
    price: 419,
  }, {
    id: 12,
    category: 'Chair',
    featured: false,
    latest: true,
    title: 'Round Short Leg Stool/Chair',
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2018/01/round-stool.jpg',
    price: 229,
  }, {
    id: 13,
    category: 'Sofa',
    featured: false,
    latest: false,
    title: 'Sofa Chairs with Cushions',
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2018/01/safa-2.jpg',
    price: 325,
  }, {
    id: 14,
    category: 'Sofa',
    featured: false,
    latest: false,
    title: 'Sofa Chairs with Red Cushions',
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2018/01/chair-1.jpg',
    price: 450,
  }, {
    id: 15,
    category: 'Table',
    featured: false,
    latest: true,
    title: 'Study Table',
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2018/01/wooden-study-table.jpg',
    price: 385,
  }, {
    id: 16,
    category: 'Chair',
    featured: false,
    latest: true,
    title: 'Vintage Luxury Chair',
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2018/01/luxury-chair.jpg',
    price: 429,
  }, {
    id: 17,
    category: 'Chair',
    featured: false,
    latest: true,
    title: 'Wingback Yellow Couch',
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2018/01/couch.jpg',
    oldPrice: 192,
    price: 186,
  }, {
    id: 18,
    category: 'Chair',
    featured: false,
    latest: true,
    title: 'Wooden Rocking Chair',
    content: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra.',
    image: 'https://websitedemos.net/furniture-store-04/wp-content/uploads/sites/155/2018/01/wooden-rocking-chair.jpg',
    price: 169,
  }
]